# Generated by Django 5.0 on 2023-12-09 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_options_rename_date_added_post_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='signature',
            field=models.CharField(default='Maxwell', max_length=140),
        ),
    ]
